jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
    maxParallel: 1
  steps:
  - bash: |
      tar --help
      tar --version
    displayName: Test in Bash
  - powershell: |
      tar --help
      tar --version
    displayName: Test in Powershell
