jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
    maxParallel: 1
  steps:
  - script: |
      brew install gnu-tar
      export PATH=/usr/local/opt/gnu-tar/libexec/gnubin:$PATH
      tar --help
      tar --version
    displayName: 'Test'
